# Generated by Django 3.0.5 on 2020-04-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_section_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.CharField(default='', max_length=5),
        ),
    ]
