# Generated by Django 3.0.5 on 2020-04-02 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200401_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Student')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Test')),
            ],
        ),
        migrations.CreateModel(
            name='QuizStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Quiz')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Student')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('homework_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Homework')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Student')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='students',
            field=models.ManyToManyField(through='courses.HomeworkStudent', to='courses.Student'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='students',
            field=models.ManyToManyField(through='courses.QuizStudent', to='courses.Student'),
        ),
        migrations.AddField(
            model_name='test',
            name='students',
            field=models.ManyToManyField(through='courses.TestStudent', to='courses.Student'),
        ),
    ]
